kpet/clvk

- src/CMakeLists.txt
This is necessary when the Vulkan headers are not in the system header
search path.
> Add ${Vulkan_INCLUDE_DIRS} to include directories

- src/api.cpp
Without this, `simple_test` crashes when no GPU devices are found.
> Return CL_DEVICE_NOT_FOUND from clGetDeviceIDs

- tests/simple/simple.cpp
This enables the test to run on Talvos.
> Don't restrict the device choice to GPUs in simple_test

- src/CMakeLists.txt
- src/device.hpp
- src/program.cpp
- src/utils.cpp
- src/utils.hpp
* Skip GCC specific attributes/flags
* Include necessary header files
* Add windows specific mkdtemp function
Note that clspv needs some compile fixes before this can work
> Fix MSVC compilation issues

- src/program.cpp
- src/utils.cpp
Fixes use of mkdtemp() on macOS.
> Move unistd.h include to utils.cpp

- README.md
- src/CMakeLists.txt
- src/program.cpp
- src/program.hpp
- tests/simple_ubo/simple.cpp
Adds Cmake option to select compile style:
* default remains separate process
* new option uses Clspv API
Changes:
* Changes to support using Clspv API
* update UBO test to meet std140 rules
I've tested the simple tests using both compiler options.
> Use clspv api through Cmake option

- src/program.cpp
Without this the `simple_image` test crashes when using online Clspv compilation. The `sampler` case is included in the other variant of `load_descriptor_map`, and I couldn't see any obvious reason why this couldn't be supported for online.
CC @alan-baker just to check there wasn't any particular reason why this was left out of PR #34 ?
> Allow samplers in descriptor map for online Clspv

- src/api.cpp
- src/memory.cpp
- src/memory.hpp
- src/queue.cpp
- src/queue.hpp
Good enough for the conformance tests but missing
some error checking.
Closes #91.
Closes #92.
> Support for buffer/image copies

- src/queue.hpp
PR #117 introduced uses of `std::array` without adding this include.
> Add missing <array> include

- src/memory.hpp
I'd recommend making all CI configs use a Debug build, both to catch this sort of thing and also so that the tests run with all assertions enabled.
> Fix build error for CMAKE_BUILD_TYPE=Debug

- src/device.cpp
- src/device.hpp
- src/program.cpp
- src/program.hpp
This produces more useful errors when a SPIR-V module produced by Clspv uses capabilities that  are not supported by the Vulkan device. These errors currently just go to the logging system, but we should also be able to put these in the build log that goes back to the application as well.
As part of this, I've made `VK_KHR_variable_pointers` an optional extension, and query which of its features are supported by the device (if any), using `vkGetPhysicalDeviceFeatures2()`. This allows Clvk to run on top of SwiftShader for kernels that do not require support for the variable pointers extension.
> Perform fine-grained SPIR-V capability checks

- src/api.cpp
- src/memory.cpp
- src/memory.hpp
- src/queue.cpp
- src/queue.hpp
- src/utils.hpp
Doesn't support CL_HALF_FLOAT channel data type.
Certainly not the fastest.
Closes #89.
> Basic implementation of clEnqueueFillImage

- .travis.yml
- tests/travis/check-format.sh
- tests/travis/step-before-install.sh
- tests/travis/step-install.sh
- tests/travis/step-script.sh
Adds a Linux-only config which runs a script that checks for formatting violations on any `.cpp` or `.hpp` files that have changed. The script can also be run locally before committing.
Note that one of the entries in the `.clang-format` config requires clang-format version 10, which isn't available by default on many platforms at present (hence the need to pull in the LLVM apt repository in the Travis script).
Example Travis CI job that fails due to bad formatting:
https://travis-ci.org/jrprice/clvk/jobs/620166482
> Check formatting via Travis CI

- CMakeLists.txt
- README.md
We will shortly be setting up a Clspv test bot that will use Clvk to run tests driven via the OpenCL API.
> Allow user to specify external Clspv source dir

- src/memory.cpp
- src/queue.hpp
Caught by an internal build platform that enables more warnings and `-Werror`.
> Build fixes

- src/device.cpp
These are required for all Vulkan implementations and are now
generated by Clspv.
> Support the Sampled1D and Image1D capabilities

- CMakeLists.txt
Aside from building stuff that wasn't actually used, this was also breaking our bots since SPIRV-LLVM-Translator doesn't yet accept LLVM 11 (which Clspv is now targeting since LLVM branched for the upcoming 10.0 release).
> Skip SPIRV-LLVM-Translator build with online Clspv

- src/CMakeLists.txt
When `CMAKE_SHARED_LINKER_FLAGS` is non-empty, this `set` command was creating a list and inserting a semi-colon, which broke the link line.
> Fix linker flags when setting --version-script

- src/device.cpp
* If the API level is less than 1.1, don't request
VK_KHR_get_physical_device_properties2 as device extension
* it is already properly requested as an instance extension
> Don't request physical device properties2 as device extension

- src/program.cpp
* Filter mode was being assigned to the wrong field
> Fix literal sampler parsing for online compiles

- src/CMakeLists.txt
- src/api.cpp
- src/cl_headers.hpp
- src/device.hpp
- src/icd.hpp
- src/kernel.cpp
- src/kernel.hpp
- src/memory.hpp
- src/objects.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
- tests/travis/step-install.sh
- tests/travis/step-script.sh
All OpenCL API objects now inherit from an `icd_object` base class which contains the dispatch table. Downcasts have been introduced as necessary to convert to the clvk subclasses.
Linking to clvk directly is still supported. The dispatch table function pointers are obtained by calling `dlsym()` on the clvk library, which circumvents having to rename the API definitions to avoid clashing with the definitions provided by the ICD loader.
This is perhaps a slightly strange approach, so let me know if you'd rather I just rename the APIs and set the function pointers directly (e.g. `m_dispatch->clFoo() = clvk::clFoo()`, which then requires an another definition of `clFoo()` which calls `clvk::clFoo()` to make direct linking work). 
The many `static_cast` calls are a little ugly; I couldn't see …
> Add ICD support

- src/kernel.cpp
- src/kernel.hpp
- src/queue.cpp
- tests/api/CMakeLists.txt
- tests/api/enqueue.cpp
- tests/api/testcl.hpp
The max number of descriptor sets was wrong.
Add a test exercising many instances in flight that measures the time
spent enqueueing the kernels.
Fixes #153
> Fix descriptor pool creation and add test

- src/queue.cpp
Using `float` for `nsPerTick` meant that some intermediate results were exceeding maximum representable values on certain devices.
> Fix timestamp queries

- src/kernel.cpp
- src/kernel.hpp
- src/queue.cpp
Fixes #157
* Changed cvk_kernel_argument_values to hold raw refcounted pointers
* Add new methods to cvk_kernel to retain and release arguments
* retain args prior to setting up descriptor sets and enqueueing
* release upon completion of the kernel
This is the simplest change to address #157 and I'd like some feedback on it if possible. I think I've made the changes suggested in the issue. I also have the suggested test with the destructor callback, but am not sure it belongs in this repo. 
I have tested this against the app that previously ran OOM due to not free'ing buffers and it passes now.
> Change how kernel args are retained and released

- src/api.cpp
Fixes "suggest braces around initialization of subobject" warning, which was triggered when OpenCL 2.x was enabled.
> Add braces for cl_image_desc union initialization

- src/queue.hpp
The `cvk_executor_thread::shutdown()` method was setting `m_shutdown` outside of the mutexed region, which causes TSAN to flag a potential data race.
I don't /think/ this is actually a problem given that `m_shutdown` is being tested again after the condition variable is signaled, but still nice to squelch the TSAN error.
> Fix data race in queue shutdown

- src/CMakeLists.txt
- tests/api/simple_ubo.cpp
This _fixes_ the build issues from:  #173 
There are two more issues in OpenCL-Headers, that are addressed separately (although the submodule needs updating then).
Also exporting all symbols through CMake is probably not the best idea and should be handled better..
> Fix the clvk-side Windows build errors

- src/kernel.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
Introduces a `cvk_entry_point` class which now owns all pipeline state (e.g. descriptor set layouts and information about POD arguments). One instance of this class is shared between all kernel objects created from the same program that target the same kernel function.
Using specialization constants as a key, a `cvk_entry_object` object holds a map of pipelines which can be reused for kernel launches that have the same work-group size and local memory argument sizes. These pipelines are destroyed when the `cvk_entry_point` object is destroyed, which occurs when the parent program object is destroyed.
There isn't a great deal of new code here, it's mostly just refactoring existing code into a new class and changing the lifetime of the Vulkan pipeline structures.
> Implement a program scope pipeline cache

- src/program.cpp
The new pipeline cache regressed a couple of CTS tests (e.g. compiler options_build_macro) since entry points (and their VkPipeline objects) were persisting after a program was rebuilt with different compiler options.
> Destroy existing entry points when rebuilding

- src/device.cpp
- src/init.cpp
- src/init.hpp
The Vulkan loader may report a newer API version than the underlying Vulkan device, so we cannot rely on the version reported by `vkGetInstanceVersion` to determine whether or not to enable the extension. Instead, enable the extension if it is present, check the device's API version at the point we use the function, and get the KHR suffixed variant via `vkGetInstanceProcAddr` if we are on Vulkan 1.0.
This change allows clvk to work over MoltenVK. I have not tested any other Vulkan 1.0 devices, but my other Vulkan 1.1 devices still work.
> Fix use of vkGetPhysicalDeviceFeatures2 for Vulkan 1.0

- src/device.hpp
- src/kernel.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
* Adds a new pod buffer in host memory for pushconstant pod args
* treated similarly to the pod buffer, but is not a VkBuffer
* adding updated descriptor map parsing
There are two commits. The first commit includes hacks to the compile to force the use of pod push constants (how I tested this). The second commit removes those options so that the new functionality is unused (as per https://github.com/google/clspv/issues/529). 
I only added infrastructure this time to reduce the size of the PR and because not all the clspv functionality is in place to do a complete switch yet. I'd appreciate feedback on whether you think this is a good direction.
> Infrastructure to support pod push constants

- tests/travis/step-before-script.sh
Should fix CI and also make the format checking job faster.
> Skip fetching deps when checking format in CI

- src/program.cpp
- src/program.hpp
This is a much simpler fix than we previously discussed in #162. Instead of using the mutex to signal when the build has completed, just rely on the fact that we already have this information in the build status. The mutex is now just used to avoid concurrent calls to clBuildProgram.
The check is slightly conservative; this doesn't allow the same program to be built for two different devices concurrently (which would be handled by the larger refactor into a cvk_program_build that we briefly discussed). I think this is fine for now however, given that the rest of the program build logic assumes single device anyway.
> Use build status to avoid concurrent builds

- src/queue.cpp
- src/queue.hpp
- src/vkutils.hpp
The command buffers of contiguous kernel commands with resolved external
dependencies are submitted together.
Contributes to #167
> Introduce primitive batching of kernel commands

- src/program.cpp
- src/program.hpp
- src/queue.cpp
* Parses module scope specialization constants in the descriptor map
* Currently supports workgroup size
* updated how workgroup size spec ids are generated
* Update clspv submodule
> Parse module-scope specialization constants

- src/program.cpp
- src/program.hpp
- src/queue.cpp
- tests/api/enqueue.cpp
* Clspv default for -work-dim is true so stop passing that option
* Parse work dim spec constant in descriptor map
* Populate work dim spec constant value if necessary
* Add test for work dims
> Support work dimensions as a spec constant

- src/program.cpp
- tests/api/enqueue.cpp
* Remove unnecessary options
* -work-dim is on by default
* -cluster-pod-kernel-args is on by default
* -pod-ubo removal allows clspv to choose implementation
* Added some tests to confirm both ubo and push constant pod args work
* Update clspv
> Remove unnecessary compile options

- src/program.cpp
- src/program.hpp
- src/queue.cpp
- tests/api/enqueue.cpp
* Parse global offset spec constants
* Provide values for global offset spec constants in kernel enqueue
* add tests for both spec constant and push constant
Clspv generates global offset as a spec constant unless `-global-offset-push-constant` is specified or the language is CL2.0 or CL C++. The latter because of all the other global data that is needed for non-uniform nd ranges.
> Support global offset as a spec constant

- src/memory.cpp
- src/memory.hpp
* Avoid modifying m_map_ptr from sub-buffers that are already mapped,
as this causes a data race with some commands that use the
pointer. Hoist the `m_map_count == 0` check out so that parent
buffers are not re-mapped either (though this was not actually an
issue).
* Avoid using m_map_count in the assertion in host_va(), as this
causes a data race with the map()/unmap() methods that inc/dec this
counter.
> Fix TSan issues around memory mapping

- src/device.cpp
- src/device.hpp
Will need more work to enable the right Clspv options once https://github.com/google/clspv/pull/580 lands.
> Enable {8,16}-bit storage extensions and features

- src/device.hpp
- src/program.cpp
* Pass features from 8- and 16-bit storage extensions to clspv storage
restriction options
> Pass storage restrictions to clspv

- src/program.cpp
These are needed for non-uniform work-groups.
> Add missing push constants for online Clspv

- README.md
- src/program.cpp
This is a useful option for developers. Sometimes I want to force clvk to run a shader that uses an unsupported capability, because I know the functionality I need is actually implemented (there might be other parts of the capability that I don't need that are not supported, hence why the device doesn't advertise the capability).
> Add CLVK_SKIP_SPIRV_CAPABILITY_CHECK option

- src/queue.cpp
Since this should be a no-op on devices that don't have this bug I figured it's OK to do this unconditionally - let me know if you disagree. I'll try to make a minimal reproducer to send to NVIDIA and add to Vulkan CTS in the meantime.
> Add workaround for NVIDIA driver bug

- src/device.cpp
- src/device.hpp
- src/queue.cpp
- src/queue.hpp
Avoids creeping memory growth (and subsequent crashes) with some drivers, and gives performance wins in some cases.
For example, the Arm Mali developer guide [says](https://developer.arm.com/documentation/101897/0200/cpu-overheads/command-pools-for-vulkan?lang=en):
> Command pools do not automatically recycle memory from deleted command buffers unless created with the RESET_COMMAND_BUFFER_BIT flag. Pools without this flag do not recycle their memory until the application resets the pool.
It later recommends *against* using `RESET_COMMAND_BUFFER_BIT` (due to potential increase in CPU overheads), but the alternative is using `vkResetCommandPool`, which is more difficult to fit into clvk right now. I didn't see any significant performance drops when using `RESET_COMMAND_BUFFER_BIT` in my own …
> Create command pool with RESET_COMMAND_BUFFER_BIT

- src/kernel.cpp
Instead of calling `vkUpdateDescriptorSets` for each kernel argument separately, collect all the `VkWriteDescriptor` structures and call it just once.
This yields significant improvements to kernel enqueue latency on some Vulkan implementations.
> Batch descriptor set updates

- README.md
- src/api.cpp
- src/queue.cpp
- src/queue.hpp
Summary:
* `cvk_command_queue` maintains a `cvk_command_kernel_group`
- Add new commands to it as long as they are batchable
- End the group when a non-batchable command is enqueued
* `cvk_command_kernel_group` has a `cvk_command_buffer`
- Used for all of its kernel commands
* `cvk_command_kernel::build()` now takes a `cvk_command_buffer` parameter
- Called by `cvk_command_kernel_group::add_kernel()`
* Non-batchable kernel commands are in their own `cvk_command_kernel_group`
- Avoids splitting batchable/non-batchable logic in `cvk_command_kernel`
* Added `CLVK_MAX_BATCH_SIZE` environment variable
- Some apps might need to limit this to avoid device timeout
- Defaults to 10000
Having `cvk_command_kernel::do_action()` be a never-called method is a little awkward. The simplest alternative is …
> Batch kernel dispatches in the same command buffer

- src/kernel.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
Summary:
* Make descriptor sets and POD buffer part of the `cvk_kernel_kernel_argument_values` structure
* Reuse existing `cvk_kernel_argument_values` instance when enqueueing
kernel with same args multiple times
* Create new `cvk_kernel_argument_values` instance when setting argument
for a kernel object that has already been enqueued
* Handle shared ownership of `cvk_kernel_argument_values` via `std::shared_ptr`
Notes:
This ended up being more intrusive than I originally imagined it would be. Some of the changes around how `cvk_kernel_argument_values` ownership and resource retention is handled are not directly related to descriptor set reuse, but I think are a little cleaner than the previous implementation (feel free to disagree!). If this is going too far, the second commit here can …
> Reuse descriptor sets between kernel launches

- .gitmodules
- src/CMakeLists.txt
- src/program.cpp
- src/program.hpp
Change clvk to use clspv's embedded reflection in the SPIR-V binary.
* Offline and online compilation now share parsing of reflection information
* "binary" returned by clvk no longer contains the descriptor map
* left the magic number to minimize overall number of changes
* if the Vulkan implementation does not support VK_KHR_non_semantic_info then the reflection information is stripped after parsing
* the stripped binary is stored separately so that the binary with embedded reflection may be returned for clGetProgramInfo
* update submodules
> Switch to use embedded reflection

- src/kernel.cpp
* Addresses clang-tidy warning
> Remove redundant get()

- src/api.cpp
- src/queue.hpp
... as required by the OpenCL specification.
Fixes #243
> Flush queues when calling clReleaseCommandQueue

- src/device.cpp
This capability is used by Clspv for read_write images.
> Handle shaderStorageImageReadWithoutFormat

- src/objects.hpp
The move constructor should invalidate the source holder's object reference to avoid decrementing the reference count when the source holder is destroyed.
This was showing up as a heap corruption for programs that contain multiple literal samplers. When the second literal sampler was [added to the `m_literal_samplers` vector](https://github.com/kpet/clvk/blob/04f1fca4a2748fb599e65ccfe38ad999115d0c26/src/program.cpp#L973), the implementation of `emplace_back` was resizing the vector and copying the elements over using the move constructor, and then the old elements were destroyed, triggering the destructor and decrementing the reference count.
> Fix refcounted_holder move constructor

- src/api.cpp
- src/device.cpp
- src/device.hpp
Start at (1,1,1) and alternately double the X and Y dimensions while it is still valid to do so, capped to a total size of 64.
It's pretty crude, but this yields huge gains on a workload that I'm looking at that uses a `NULL` work-group size. I've left TODOs for some of the many potential areas for improvement in the comments.
Contributes to #265.
> Add a simple work-group size selection heuristic

- README.md
- src/device.cpp
- src/device.hpp
- src/program.cpp
- src/program.hpp
If the user sets the `CLVK_CACHE_DIR` environment variable to a non-empty value, clvk will write Vulkan pipeline data to a per-device file in that directory during teardown. On the next run, clvk will load pipeline cache data from this directory and use it to seed the initial pipeline cache.
This also changes the Vulkan pipeline cache to be device-scope, rather than program scope. We could keep using per-program pipeline caches if we serialized them all separately (during program teardown), but we'd need to hash the SPIR-V to uniquely identify them. I didn't want to go this route just yet since it would probably add an additional dependency for the hash function (unless we rolled our own...).
This provides significant performance improvements (1.5-1.8X) for part of a workload that I'm …
> Add support for pipeline cache serialization

- src/program.cpp
We've already run SPIR-V validation manually just before this, so we
don't need to do it again.
> Skip extra validation when stripping reflection

- src/memory.hpp
Prevents invalid calls to vkFreeMemory upon destruction for memory
allocations that failed.
This was causing tests in allocations CTS suite to crash on some platforms.
> Initialize memory allocation pointer

- src/api.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
* Parse the PropertyRequiredWorkgroupSize extended instruction and
store the required work-group size
* Implement the CL_KERNEL_COMPILE_WORK_GROUP_SIZE query
* Check the requested work-group size against the required work-group
size during kernel enqueue
Closes #50.
> Handle reqd_work_group_size attribute

- CMakeLists.txt
- tests/azure/pipeline-precommit.yml
- tests/azure/steps-build.yml
- tests/azure/steps-fetch-sources.yml
Building with LLVM_TARGETS_TO_BUILD set to an empty string is broken again:
CMake Error at external/clspv/third_party/llvm/llvm/cmake/modules/LLVM-Config.cmake:31 (list):
list sub-command REMOVE_ITEM requires two or more arguments
until this is resolved upstream, set it to contain at least one target.
Also update the Vulkan Loader version and move to Windows 2019 in the CI.
> Work around LLVM CMake issue and update CI

- src/program.cpp
- src/program.hpp
- tests/api/compiler.cpp
- tests/api/images.cpp
- tests/api/simple_image.cpp
- tests/api/testcl.hpp
Otherwise push constants, spec constants, and required work-group size information will not be present in the linked binary.
This fixes some CTS regressions introduced by #283. The Clspv update is needed for a recent bugfix that affects the test case added in this PR.
> Parse reflection info after linking programs

- src/api.cpp
- tests/api/images.cpp
- tests/api/testcl.hpp
Fix clEnqueueWriteImage with offsets
* Do not apply `origin` as an offset when copying from the host
pointer to the staging buffer.
* Use the region size instead of the image size when calculating
default pitches.
Added a test for this.
> Fix clEnqueueWriteImage with offsets

- src/api.cpp
- src/queue.cpp
- src/queue.hpp
- tests/api/enqueue.cpp
Always keep the last event produced as part of sending work to the
executor in the queue. Wait on that event in clFinish.
The test is not bullet-proof (hard to guarantee that the thread
about to call clFinish is blocked without blocking) but in my tests
failed 100% of the time before the fix and passed 100% of the time
after.
Fixes #241
> Fix clFinish when called just after clFlush

- src/objects.hpp
Without this, `_cl_context` is not a complete type, which causes build failures since it is used as a base class in this file. The `icd.hpp` include was previously happening indirectly via `device.hpp`, but that include was removed in 3961358.
> Add missing icd.hpp include in objects.hpp

- src/api.cpp
... in accordance with [the specification](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetKernelArgInfo.html), in **Errors** section
> Return CL_KERNEL_ARG_INFO_NOT_AVAILABLE in clGetKernelArgInfo

- src/device.cpp
- src/program.cpp
Update clspv to be able to use the corresponding option.
> Support cl_arm_non_uniform_work_group_size

- README.md
- src/program.cpp
Let the user skip validation or ignore errors using the CLVK_SPIRV_VALIDATION environment variable.
> Control SPIR-V validation through env variable

- src/api.cpp
- src/queue.cpp
- src/queue.hpp
- Any command that just submits a command buffer can now be batched
- Query pools are used to profile all batchable command generically (when supported)
- Batchable commands are built on enqueue
> Generalise command batching

- src/api.cpp
- tests/api/images.cpp
Kernel-side support covered by #304
Also improve/speed up how image formats are handled.
Fixes #303
> Partial support for CL_LUMINANCE image formats

- src/api.cpp
There were two small bugs:
* Single task enqueue was launching (1, 0, 0) instead of (1, 1, 1)
* The 3rd dimension of CL_KERNEL_COMPILE_WORK_GROUP_SIZE was incorrect
> Fix two bugs from cvk_ndrange commit

- src/kernel.hpp
- tests/api/CMakeLists.txt
- tests/api/local_buffer.cpp
In OpenCL CTS 'vstore_local', we have this pattern:
```
for (args - last_arg) {
clSetKernelArg(arg)
}
for (various alignmentOffset){
clSetKernelArg(last_arg, alignmentOffset);
clEnqueueNDRangeKernel();
}
```
When we clSetKernelArg the second time. As the kernel has been enqueue
once, we will create a new cvk_kernel_argument_values in
cvk_kernel::set_arg. And we will lose information about the local
buffer argument, which led to a local buffer with the wrong size.
Let's copy the needed information in order to ensure that the local
buffer will always have the proper size.
> fix for local buffer argument in kernel prototype

- src/api.cpp
- src/memory.cpp
Without this, `clCreateImage()` returns `CL_OUT_OF_RESOURCES`. The difference between `CL_LUMINANCE` and `CL_INTENSITY` lies in the fourth component, when for example reading into a `float4`. Unfortunately, I cannot find the place where this is handled (if at all?).
> Support CL_INTENSITY image format

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/azure/job-precommit.yml
- tests/azure/pipeline-precommit.yml
- tests/azure/steps-build.yml
- tests/azure/steps-run-tests.yml
- tests/simple-from-il-binary/CMakeLists.txt
- tests/simple-from-il-binary/simple.cl
- tests/simple-from-il-binary/simple.cpp
Tests using clCreateProgramWithILKHR extension when
CLVK_CLSPV_ONLINE_COMPILER is disabled. Added simple-from-il-binary
test is based off of the existing simple-from-binary test.
Contributes to #45.
@DCastagna @jrprice
> Add test that loads program from IL Binary

- CMakeLists.txt
- src/CMakeLists.txt
- src/device.cpp
- src/program.cpp
- tests/CMakeLists.txt
- tests/azure/steps-build.yml
- tests/azure/steps-run-tests.yml
Adds support for the cl_khr_il_program extension in online
compilation mode by using the readSpirv api from
SPIRV-LLVM-Translator and clspv::Compile.
Closes #45.
@DCastagna @jrprice
> Support IL binaries in online compilation mode

- src/api.cpp
- src/device.cpp
- src/memory.cpp
- src/memory.hpp
cl_image use the vkMemory from the cl_buffer.
it only works if the device host visible memory is also device local
memory so that the memory can be bind by vulkan to the vkImage.
> add support for CL_MEM_OBJECT_IMAGE1D_BUFFER

- CMakeLists.txt
- README.md
- tests/CMakeLists.txt
- tests/conformance/CMakeLists.txt
- tests/sha1/CMakeLists.txt
- tests/simple-from-binary/CMakeLists.txt
- tests/simple-from-il-binary/CMakeLists.txt
- tests/simple/CMakeLists.txt
- SPIRV-LLVM-Translator path can be overriden
- tests/CMakeLists.txt can be used on its own
- Static tests can be disabled with CLVK_BUILD_STATIC_TESTS
- LLVMSupport is added only when BUILD_SHARED_LIBS=ON
> cmake changes to ease in chromeos infrastructure

- src/kernel.hpp
- src/program.cpp
- src/program.hpp
If a argument is a vec3, OpenCL requires the size passed to
clSetKernelArg to be 4 times the element size. Accept it even so clspv
arg size is 3 times the element size.
> fix vec3 arg size check in clSetKernelArg

- CMakeLists.txt
- src/CMakeLists.txt
- src/device.cpp
- src/device.hpp
- src/exports.map
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
- src/unit.cpp
- src/unit.hpp
- src/utils.hpp
- tests/CMakeLists.txt
- tests/api/CMakeLists.txt
- tests/api/split_region.cpp
- tests/azure/pipeline-precommit.yml
When a region is bigger than the vulkan limits, we need to split it in
smaller region to execute it.
Do that only if we are using 'region_offset' and 'region_group_offset'
otherwise it won't work properly.
Add a test for it. The test is using a export function that is not
part of OpenCL and thus not really documented that allow to change the
vulkan limits. It enables the test to make sense without having to
know the physical limits and to run in a short amount of time. This
function is an extern C function not to have to consider the mandling
in 'exports.map'. Shall not be used appart from this test.
Fix #266
> Split region that are bigger than vklimits

- src/program.cpp
- tests/simple-from-il-binary/simple.cl
llvm::readSpirv assumes that the input stream containig SPIR-V is seekable.
In particular, when the input SPIR-V contains an OpType* that gets parsed
with SPIRVDecoder::getContinuedInstructions, tellg() and seekg() are called
on the istream.
This CL adds seeking support to the stream we pass as input of readSpirv.
> Fix istream passed to readSpirv

- src/CMakeLists.txt
This allows straightforward replacement and easy use of install_name_tool down the road to use this on existing application binaries.
> Define OpenCL as an application framework on Apple OSes.

- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/unit.cpp
- tests/api/split_region.cpp
Looking for region_offset and region_group_offset to know if we can
split the region is not enough as a test using only one of them can
still be split. But it will not be accepted by clvk with the current
test.
Instead let's looking into the kernel options to choose whether we try
it or not.
Also round_up the size of the workgroup to the local size in order to
keep region uniform.
> Fix 65fef82 (split of region bigger than vklimits)

- src/utils.hpp
some platform have maxComputeWorkGroupCount equal to UINT_MAX.
It generates an overflow when computing num_splitted_regions in
cvk_command_kernel::dispatch_uniform_region_iterate
> fix ceil-div to avoid overflow

- src/memory.cpp
- src/memory.hpp
- tests/api/images.cpp
Add a test which is segfaulting without this fix due to a double free.
> memory: fix free of cvk_memory_allocation when using image1dbuffer

- src/api.cpp
- src/device.cpp
- src/device.hpp
- tests/api/CMakeLists.txt
- tests/api/platform.cpp
- Report the first device as the default device and add a test that checks
exactly one default device is reported.
- Support enumeration when application pass a mask of device types with
multiple bits set and add a test.
> Fix device enumeration logic and add tests

- src/program.cpp
- src/program.hpp
It's possible for clspv to generate UBO layouts that require VK_KHR_uniform_buffer_standard_layout. If the device supports it, tell the SPIR-V validator.
This fixes `basic/parameter_types` from the CTS when combined with this clspv fix - https://github.com/google/clspv/pull/886
> Allow standard layout for UBOs when validating the SPIR-V if supported

- src/program.cpp
In ONLINE compilation mode, clspv does not include any path by
default (which it does with the input path in OFFLINE compilation
mode).
Explicitly add tmp folder to cover this case
> Explicitly include tmp folder for ONLINE compilation

- src/api.cpp
- src/kernel.cpp
- src/memory.cpp
- src/memory.hpp
- No longer report them as supported for read-write images.
- Set up separate image views for sampled and storage images.
Fixes #384
> Fix handling of CL_LUMINANCE and CL_INTENSITY formats

- src/CMakeLists.txt
- src/event.cpp
- src/event.hpp
Also add an event.cpp to include event.hpp to ensure the file can be
included without needing to include dependent headers first.
> Add missing headers to event.hpp

- tests/api/images.cpp
utils.hpp has been added to use ARRAY_SIZE at some point in #387.
In the end, ARRAY_SIZE was not used but utils.hpp was still there.
Remove it as it is not needed, and on top of that, it is making the
clspv ci fail, as we are just lucky in clvk that the build system
managed to find "vulkan/vulkan.h" (which is a dependency of
"utils.hpp") while it should not be needed to build cl tests.
> tests: api: images.cpp: remove include of utils.hpp

- src/queue.hpp
This method is needed to avoid asserting on cvk_command virtual
implementation.
Ref #411
> cvk_command_dep: add memory_objects method

- src/program.cpp
we need to check for only the push constant range, not the whole pod
buffer as every pod will not be in the push constants.
#413
> fix check for max push constants size

- tests/CMakeLists.txt
`tests/api/split_region.cpp` has a dependency on `utils.hpp` for
`ARRAY_SIZE`.
And `utils.hpp` has a dependency on `vulkan.h`. This header is not
always in the includes path, making the build fail.
> fix build of api_tests

- src/CMakeLists.txt
- src/config.cpp
- src/config.def
- src/config.hpp
- src/device.cpp
- src/init.cpp
- src/init.hpp
- src/log.cpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
Keep it really simple, stupid for now. Going forward we should:
- Add support to load the configuration from a file (environment variables would still be usable and would take precedence).
- Generate documentation for all config options from the option definitions.
- Better validate inputs and support error handlers.
- Support enumerated types.
- And probably more ...
> Centralise management of configuration options and environment variables

- src/api.cpp
- src/config.def
- src/device.cpp
- src/device.hpp
- src/queue.cpp
- src/queue.hpp
add more config values to configure clvk:
- max_first_cmd_batch_size
- max_cmd_group_size
- max_first_cmd_group_size
Those configs have default value on a device level
Keep track of the number of batch enqueued to be able to have a
smaller one when no batch has been enqueued to allow the GPU to start
computing earlier.
Keep track of the number of groups sent to the executor to be able to
have early flush of smaller group to allow an early execution of
commands.
> allow smaller batch and early flush

- src/program.cpp
Intel devices fail with `OpUMulExtended` instruction. So, we should use `-hack-mul-extended` to avoid failures on Intel devices. This fixes `integer_ops/integer_mul_hi`, `integer_ops/integer_mad_hi` and `integer_ops/integer_mad_sat` CTS tests on Intel devices.
> Add -hack-mul-extended option for intel devices

- src/api.cpp
- src/device.cpp
- src/device.hpp
I've added a query to the Vulkan physical device to check if atomics are actually supported on the device. Atomic semantics like Acquire and Release are described as part of the Vulkan memory model so I believe that this is the best way to test that.
> Used vulkan memory model to query atomic capabilities

- src/device.cpp
Since we query the memory model device properties we should probably wire it up to the SPIR-V capabilities check as well.
> Add case for memory model SPIR-V capability

- src/kernel.cpp
- src/kernel.hpp
This fixes test_api/clone_kernel from the CTS
> Preserve arg set status when cloning a kernel

- src/kernel.cpp
- src/program.cpp
- src/program.hpp
I think this makes it clearer that the enum is used for both read_write
and write_only (and that both are represented with a vulkan read/write
capable type) while adhering to the existing convention.
> Rename image kernel arg kind enums.

- src/api.cpp
- src/device.cpp
Removing this extension allows us to stop reporting CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS as true while still reporting support for core subgroup functionality. This is more in line with Vulkan subgroups, specifically Vulkan's lack of any such forward progress guarantees. See #451 for more detail.
> Stop reporting support for cl_khr_subgroups extension.

- src/device.cpp
- src/program.cpp
Use the device list of OpenCL C optional features to populate the "enable-feature-macros" clspv option.
> Populate list of enabled feature macros from the devices list.

- src/memory.hpp
- src/queue.cpp
The spec does not really specify what the behaviour should be here (see https://github.com/KhronosGroup/OpenCL-Docs/issues/165).
Assume that mappings are always removed in the order they were created.
Also log the command type for commands about to be executed.
Fixes #404.
> Support multiple image mappings with the same pointer for images with CL_MEM_USE_HOST_PTR

- src/device_properties.hpp
clvk/src/device_properties.hpp:42:5: error: 'cvk_device_properties' has virtual functions but non-virtual destructor
> fix error with -Wnon-virtual-dtor

- src/device.cpp
- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
strcmp if statement was incorrectly moved by previous commit use explicit comparison for strcmp
use strncmp instead of strstr for Intel
overriden functions were not used because of copy of struct. Use a unique_ptr instead.
> fix device_properties + add amd

- src/device.cpp
- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/program.cpp
Also refactor build option handling so that options which don't vary per program are only set up once in the device rather than for each program built.
Depends on https://github.com/kpet/clvk/pull/474 (I'll pull the fixes soon)
> Take advantage of clspv's --use-native-builtins flag

- src/api.cpp
- src/device.cpp
- src/device.hpp
Sorry I missed this when doing the previous PR. This change should make the feature macro list line up with more with the API query as seen here
https://github.com/kpet/clvk/blob/782818384cec4d09cc6b3a75396959475572e1af/src/api.cpp#L791-L797
> align atomic feature macros to api query

- src/device.cpp
Fix spirv_new/cpacked-struct CTS test by passing -rewrite-packed-structs option
**This PR depends on [this clspv PR](https://github.com/google/clspv/pull/940)**
**This contribution is being made by Codeplay on behalf of Samsung.**
> Add -rewrite-packed-structs option

- .github/workflows/presubmit.yml
- src/api.cpp
- src/log.cpp
- src/log.hpp
- src/memory.cpp
- src/memory.hpp
- tests/conformance/results-kpet.json
Prepare dedicated usage flags for each buffer/image.
Also restrict CI push trigger to the main branch by default.
Contributes to #122
> Check format feature flags before reporting an image format as supported

- src/queue.hpp
clvk_command_batchable is being inherited from so it should have a virtual destructor.
> added missing virtual from command_batchable destructor

- src/queue.cpp
During command image init construction, we call enqueue_command with a _cl_event in parameter.
We will retain this event in enqueue_command because we associate this pattern as an event from userspace that needs to be retained automatically.
But we have no release associated with this.
Fix #480
> fix memory leak with command image init

- .github/workflows/presubmit.yml
- src/api.cpp
- src/config.def
- src/device.cpp
- src/device.hpp
- src/kernel.cpp
- src/kernel.hpp
- src/memory.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
This enables use of physical addressing for global memory.
Requires the relevant clspv change: https://github.com/google/clspv/pull/954
I wasn't sure whether we want this to be enabled by default at this stage, so for now it requires `CLVK_PHYSICAL_ADDRESSING=1` to enable
> Add support for using buffer device addresses

- src/config.def
- src/device.hpp
Add an option so that users could control the amount of total memory used by clvk on allocations.
> Add support to use a percentage of total memory 

- .github/workflows/presubmit.yml
- src/api.cpp
- src/device.cpp
- src/kernel.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
- tests/simple-from-il-binary/simple.cl
Fixes https://github.com/kpet/clvk/issues/479
* Preparation for clspv switching to opaque pointers by default
* Parse the NumArguments kernel operand from clspv reflection
* Use that to pre-generate all of the arguments as unused arguments
* Used arguments get overridden by the correct data after parsing
* Support unused arguments (i.e. don't error) in a few places in clvk:
* allow nullptr arg values
* ignore them when creating descriptor layouts
* ignore them when generating push constant ranges
The committed version of clspv will generate the NumArguments reflection info, but still generates reflection for unused arguments. I have tested a version of clspv that no longer generates reflection arguments in those cases and it works as expected. This will be necessary for some opaque …
> Handle kernel arguments not generated by clspv reflection

- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
vendorID/deviceID are more reliable to identify which device properties to select.
> use vendorID/deviceID to choose device properties

- src/memory.cpp
* VUID 01073 requires the sampler mipmapMode to be set to nearest if unnormalized coordinates are used
Unlikely to have any practical effect since the min and max LODs are set to 0 already, but avoids a validation error. See https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkSamplerCreateInfo-unnormalizedCoordinates-01073.
> Set mipmap filtering to nearest for unnormalized coords

- src/kernel.cpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
Add support for passing the module constants buffer as a device address push constant, so it can be used as a physical storage buffer.
This depends on this clspv change: https://github.com/google/clspv/pull/974
And the following update to the ClspvReflection instructions:
https://github.com/KhronosGroup/SPIRV-Headers/pull/308
https://github.com/KhronosGroup/SPIRV-Registry/pull/178
**This change is complete, but is marked as a draft as it depends on #453 which isn't merged yet. Only the top commit is relevant to this PR. I'm putting it up now to give context to help with the review of the ClspvReflection change.**
> Physical module constants

- src/device_properties.cpp
use native implementation of fma. Swiftshader seems to have a bug with floating point operation (involving nan and inf) which prevent it to pass the cts fma test using the software implementation from libclc
> add device_properties for swiftshader

- src/device_properties.cpp
isSwiftShaderDevice was bug, this is fixing it.
Also update the list of native builtins passing the CTS.
add device properties for nvidia withthe list of native builtins passing the CTS.
> add device properties for nvidia and fix swiftshader

- README.md
- src/config.def
- src/device.cpp
- src/device_properties.cpp
- src/device_properties.hpp
CLVK_CLSPV_LIBRARY_BUILTINS: it allows to disable the use of native builtins coming from device properties
CLVK_CLSPV_NATIVE_BUILTINS: it allows to enable to use of native builtins that are not in device properties
> add config variable to manage native builtins

- tests/api/images.cpp
The test is known to be a little flaky.
This PR is changing a bit the nature of the test.
It is checking that the map region is not written by clvk before being given to the user. But it does not check for other copies that could happen inside clvk.
> rework api_tests image write invalidate

- CMakeLists.txt
- src/api.cpp
- tests/conformance/results-kpet-full.json
- Disable Generic Address Space. There are too many CTS regressions.
- Make the SPIRV LLVM Translator use the version of SPIRV Headers tracked by clvk
Change-Id: Ia07f0882474d366f138b2e2ee88dec7c6fc962e5
> Update deps and CTS

- src/queue.cpp
- src/queue.hpp
- tests/api/dependencies.cpp
Allow main thread to steal commands from the executor when main thread reaches a clFinish call, a clWaitForEvents call or a blocking enqueue command.
For clWaitForEvents, execute instead of executor only if all events are associated to one unique queue.
extract_cmds_dominated_by has a boolean to extract only non-batch commands. It will be very important when clvk will be able to use timeline semaphore.
> allow main thread to exec instead of executor

- src/api.cpp
- src/kernel.hpp
- tests/api/compiler.cpp
We rely on the arg info to provide the argument type information for unused arguments. This in turn is required to handle errors.
Change-Id: I44e5a532d06d256fcf114bc13ba52dcdd71a16e4
> Add tests for unused kernel arguments and handle error cases

- CMakeLists.txt
- README.md
- src/CMakeLists.txt
- src/config.def
- src/device.cpp
- src/program.cpp
Keep it enabled by default
According to the OpenCL specification, just removing it from the list returned by CL_DEVICE_IL_VERSION should be enough.
This is useful for ChromeOS to remove dependency on LLVM-SPIRV-Translator as it is not strictly needed for OpenCL compliance and we do not have a use for it.
> add option to disable dependency on LLVM-SPIRV-Translator

- src/memory.hpp
- tests/conformance/results-amd-7950x.json
- tests/conformance/results-intel-a750.json
Both command enqueue and execution need to mutate mappings and they can be concurrent.
Change-Id: Ic94b2a4ddb6170e1ed1b74399d51e9f39df1d3b7
> Protect changes to memory object mappings with a mutex

- src/api.cpp
- src/device.cpp
- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/log.cpp
- src/log.hpp
I've used the name from the PCI DB in cases where the selection is made using a PCI Vendor ID.
Contributes to #10
Change-Id: I9ca4aaccfa05738d25268738b61b8c9ee8bc56ad
> Basic implementation for CL_DEVICE_VENDOR

- src/memory.hpp
Flagged by validation layers. The descriptor type does not depend on the flags of the memory object at all. This was introduced by mistake as part of fixing image usage flags...
Change-Id: I5afa823ed073e3b9326ca9d7204d7c958b5280e7
> Fix buffer usage flags

- src/memory.hpp
- src/queue.cpp
- src/queue.hpp
Buffer mappings are created at command creation time. When the command fails execution, either directly or because its dependencies failed, the mapping needs to be destroyed.
Caught by the Vulkan validation layers.
Change-Id: I53eef3c4bc4c7f4c5f94ade39b16bde558e9da2c
> Tidy up mappings when buffer map commands fail to execute

- src/program.cpp
Doing it multiple times leads to duplicated bindings for literal samplers.
Keep the call that is in the path common to online and offline compilation.
Caught by the Vulkan validation layers.
Change-Id: I8cc43d0d4f84931a85ea616ad3ba7487fcc1a8a4
> Only load SPIR-V reflection information once

- src/api.cpp
- src/kernel.hpp
- src/program.cpp
- src/program.hpp
This PR is a clean rebase of #489.
With an update of clspv to get https://github.com/google/clspv/pull/1143
I have checked the implementation on both swiftshader and nvidia. It fixes `test_api kernel_attributes`.
Fixes #398
> Implement clGetKernelInfo with CL_KERNEL_ATTRIBUTES 

- src/queue.cpp
building the command in satisfy_data_dependencies is not needed.
The command is enqueued just after. During the enqueue the command will be either built as a batchable command (in
`cvk_command_queue::enqueue_command`), or built when it will be added to a batch (in `cvk_command_batch::add_command`).
> remove unneeded build in satisfy_data_dependencies

- src/api.cpp
The api_query_string is destroyed before we copy from it. Should have been caught in testing/code review.
Change-Id: I4998d9b2518f10e2e1efbee4b42edc0014561432
> Fix CL_KERNEL_ATTRIBUTES query

- src/queue.cpp
Catching the opposite would require adding state to cvk_command_batchable but it's a much harder mistake to make so probably not worth it.
Change-Id: I2a010f1e157a4713ef6da907c9b45f4ff2defaf2
> Assert when a batchable command in built into a batch after being built as standalone

- src/queue.cpp
build_batchable_inner always return a proper CL error code. Use it instead of overwriting to CL_OUT_OF_RESOURCES to keep as much information as possible.
Also add a error log
> do not override build_batchable_inner error code

- src/api.cpp
- src/device.cpp
- src/device.hpp
- src/device_properties.hpp
- src/memory.cpp
- src/memory.hpp
This will help once we have something detected whether or not to use physical addressing.
It will also help force some device to not use physical addressing if the feature is bugged.
> manage spirv_arch & physical_addressing in device/device_properties

- src/kernel.hpp
We used to free descriptor sets when cvk_kernel_argument_values is destroyed. But as cvk_kernel has a ref on it, it is only freed when clReleaseKernel is called.
To be able to free them earlier, keep a refcount between retain_resources and release_resources. When the counter reach zero, free the descriptor sets, and set m_is_enqueued to false to make sure we reallocate the descriptor set if we need to use them once again.
As descriptor sets can be allocated after being freed, reset them to VK_NULL_HANDLE.
> free descriptor sets in cvk_kernel_argument_values earlier

- src/kernel.hpp
I found this bug running api_tests on llvmpipe with physical addressing enabled.
api_tests: WithContext.SetUnusedMemeObjectArgWithInvalidObject failed
> fix set_arg with invalid pod pointer

- .clang-format
Since clang-format-15 InsertBraces can be used to force brace around single line control statement.
> clang-format: InsertBraces = true

- .github/workflows/presubmit.yml
- tests/check-format.sh
Since we use InsertBraces, we need to use at least clang-format-15. But only installing clang-format-15, does not pull git-clang-format with it.
So let's install both clang-format and clang-format-15, and force it to use clang-format-15 to ensure that InsertBraces is supported
> fix clang-format usage

- src/config.hpp
compiling on arch-linux with gcc-13 failed on this missing header
> add missing header in config.hpp

- .github/workflows/presubmit.yml
- src/log.cpp
While stdout is line buffered and stderr is unbuffered, file are just buffered by default.
Which means that fatal and error logs might not be printed (or completely printed) in some scenario.
> force flush fatal and error logs

- docs/supported-applications.md
Hashcat information mode works
```
$ LD_LIBRARY_PATH=./build hashcat -I
hashcat (v6.2.6) starting in benchmark mode
...
OpenCL Info:
============
OpenCL Platform ID #1
Vendor..: clvk
Name....: clvk
Version.: OpenCL 3.0 clvk
Backend Device ID #2
Type...........: GPU
Vendor.ID......: 32
Vendor.........: NVIDIA Corporation
Name...........: NVIDIA GeForce RTX 3070 Ti
Version........: OpenCL 3.0 CLVK on Vulkan v1.3.242 driver 2245361984
Processor(s)...: 1
Clock..........: 0
Memory.Total...: 8192 MB (limited to 1024 MB allocatable in one block)
Memory.Free....: 8064 MB
Local.Memory...: 48 KB
OpenCL.Version.: OpenCL C 1.2 CLVK on Vulkan v1.3.242 driver 2245361984
Driver.Version.: 3.0 CLVK on Vulkan v1.3.242 driver 2245361984
```
However, when attempting to run a benchmark, the kernel fails to …
> Hashcat Kernel fails to compile

- src/printf.cpp
- tests/api/printf.cpp
According to the OpenCL specification, when printing a vector if the modifier is not used, it is an undefined behavior. The current implement prints the first element only: "%v4u", (1, 2, 3, 4) => '1, 1, 1, 1'
But in our case we can figure out the element size using information coming from clspv. Use it only when we are in this undefined behavior to print something making more sense:
"%v4u", (1, 2, 3, 4) => '1, 2, 3, 4'
> fix print when forgetting vector modifier

- src/api.cpp
- src/device.cpp
- src/device.hpp
- src/kernel.cpp
- src/memory.cpp
- src/memory.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- src/queue.hpp
- tests/api/images.cpp
- tests/api/testcl.hpp
This implementation has been tested using the OpenCL-CTS patch with https://github.com/KhronosGroup/OpenCL-CTS/pull/1806
> add support for image1d_buffer

- src/kernel.cpp
- src/kernel.hpp
- src/memory.cpp
- src/memory.hpp
- src/program.cpp
- src/program.hpp
- src/queue.cpp
- tests/api/images.cpp
This PR depends on google/clspv#1234
We parse the new NormalizedSamplerMaskPushConstant non-semantic instruction from KhronosGroup/SPIRV-Headers#377.
Set the sampler mask in the push constant, but also create a new sampler with normalised coordinate if not already the case or already created.
> fix support for read of 3D images with unnormalised sampler

- src/unit.cpp
> Make unit testing symbols available even in the case if unit tests are disabled.

- src/CMakeLists.txt
- src/api.cpp
- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/image_format.cpp
- src/image_format.hpp
- src/memory.cpp
also fix condition for CL_LUMINANCE and CL_INTENSITY (ref #625)
> add fixup for image1dbuffer with bgra format on Intel

- src/api.cpp
This OpenCL commit renamed some macros:
https://github.com/KhronosGroup/OpenCL-Headers/commit/8de09e8f07e3272da06e62358a8116c27d235036
This breaks importing OpenCL into google internal, so fixing upstream.
> Update OpenCL dep

- src/device_properties.cpp
Both Intel and AMD GLSL fabs version flush denormalized numbers to zero.
This will prevent OpenCL compliance when clspv will be updated with google/clspv#1252 as functions like cbrt from libclc requires denormalized numbers not to be flushed to zero to be compliant.
> remove fabs from native_builtins for intel and AMD

- src/program.cpp
This is very useful when running with opencl-kernel-profiler and vulkan-shader-profiler to easily reproduce offline the compilation flow.
> add perfetto trace for build_options

- src/api.cpp
- src/device.hpp
We need at least StorageImageReadWithoutFormat to support read write images.
> only report read-write images if we have theright spirv capability

- src/program.cpp
- src/queue.cpp
- src/utils.cpp
- src/utils.hpp
We are having issue in google infra with native_handle_type which is
not supported.
> rework thread naming to avoid requiring native_handle_type

- CMakeLists.txt
- src/CMakeLists.txt
- src/exports.map
- src/unit.cpp
- src/unit.hpp
- tests/api/enqueue.cpp
- tests/api/printf.cpp
- tests/api/testcl.hpp
- Fix printf tests so they don't mutate the global config with impact to other tests. Restore the config at the end of the test.
- Check assumptions tests make on config values.
Tests from the API suite CANNOT be run in parallel with the current implementation.
Change-Id: I22a7bbae4ae13b224fa094bd5d01a97e8fd4e5c0
> Add utilities to write tests that assume or require specific config options

- README.md
- src/config.def
- src/memory.cpp
This is needing for some platform to pass CTS as linear filtering is not required.
> allow to disable support for sampler with linear filtering

- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/image_format.cpp
- src/image_format.hpp
Some Intel drivers have bug with CL_UNORM_SHORT_565. As it is not mandatory for OpenCL, just report it as unsupported for Intel.
> add list of unsupported image_format in device_properties

- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/image_format.hpp
- Use an unordered_set and existing functors from image_format.hpp
- Rename the device properties function to match the users
- Use function scope static objects to store the set of disabled formats
Change-Id: I9e3b5a66bae9abd29ce8e41e74ea9e2ad7c8df0b
> Tidy up management of per-device disabled image formats

- README.md
- src/api.cpp
- src/config.def
- src/device.cpp
- src/device.hpp
- src/device_properties.cpp
- src/device_properties.hpp
- src/program.cpp
- src/program.hpp
- tests/api/CMakeLists.txt
- tests/api/subgroup_size.cpp
- tests/api/testcl.hpp
This PR fix an issue on Intel device where the subgroup size used by the compiler is not the default one exposed by the vulkan driver through `m_subgroup_properties.subgroupSize`. It leads to error when running CTS `test_api sub_group_dispatch` as the expected number of subgroup does not match the one seen during execution.
To fix that, this PR uses
`VkPipelineShaderStageRequiredSubgroupSizeCreateInfo` to force the subgroup size used by the compiler.
Doing so, it breaks TFLite because it assumes that the subgroup size is always 16. Which used to work by luck because it was the size used by the compiler for the kernel using subgroups on application I have tried.
But now the default size exposed by vulkan is 32, thus kernels are compiled with subgroup size of 32.
To avoid breaking TFLite, …
> fix subgroup support & add partial support of cl_intel_subgroups

- src/memory.cpp
When filter_linear is not supported, we fallback on filter_nearest, but we should not change m_filter_mode as the API would not be reporting what has been specified during sampler creation.
> fix filter_linear support

- src/config.def
- src/queue.cpp
- tests/api/enqueue.cpp
When using hardware that override max_first_cmd_group/batch_size in device_properties, this test is not passing.
As those properties are set much before the scope of the test and are not reevaluate later, we cannot override them in the test.
Fix the test by adding a not config to prevent early flush when testing.
> fix WithCommandQueue.EnqueueTooManyCommands

- src/device.cpp
Have not deep dived into the implementation but we pass the CTS tests.
Fixes #312
Change-Id: I2ef347b7d0144c9be2d059993898ef96a65ab0e5
> Support cl_khr_spirv_linkonce_odr

- tests/perfetto/check-perfetto-trace.sh
We can sometimes have `event_wait` slice in perfetto trace. Just remove them from it to avoid flake.
> fix perfetto test flakes

- README.md
- src/config.cpp
Some builds require the clvk.conf file to be under /usr/local/etc/ this change addresses that.
> Add /usr/local/etc/clvk.conf to config file paths

- src/api.cpp
- src/program.cpp
- src/program.hpp
If no callback is given, do not build in a thread. The goal is to make perfetto more readable by reducing the number of thread used only for a very small instant.
It may also reduce build time, but honestly this is less than 1%.
> Avoid creating a thread to build program when not needed

- src/queue.cpp
Since we are able to fail an enqueue to retry later on, we have a scenario where `m_command_buffer` has been allocated during `add_command` (in `cvk_command_batch`) but the `build` has failed. Then, in `enqueue_command_with_retry` we can end up calling `end_current_command_batch` which would try to enqueue an empty command buffer.
This scenario leads to different issues later on in the flow with the command buffer trying to be executed while not having any command in it.
> fix end_current_command_batch following enqueue_retry implementation

- README.md
- src/config.cpp
It makes more sense to start from the most global location, which means starting with `/etc/clvk.conf`.
> change file config order

- .github/workflows/presubmit.yml
- README.md
- src/tracing.hpp
The perfetto::CounterTrack no longer accepts const char* track names (https://android-review.git.corp.google.com/c/platform/external/perfetto/+/3092179/5/CHANGELOG). Fix TRACE_CNT_VAR_INIT() to use perfetto::DynamicString() for track name as the name is std::string.
> fix TRACE_CNT_VAR_INIT() for Perfetto uprev

- src/device_properties.cpp
- This issue was introduced with clspv update: https://github.com/google/clspv/commit/0f43a2a7bd66ebae38b48de549299cfe4a5ebbe8
- Using the software version of fabs to meet the OpenCL Compliant
> remove fabs from native_builtins for Samsung

- README.md
- src/config.def
- src/device.cpp
The goal is to be able to enable extensions that are not fully supported by clvk, but enough for some applications.
> add config option to expose device extensions

- tests/api/images.cpp
Depending on values in device_properties, some platform can perform the unmap when the function is called, not when the app calls clFinish.
Force this behavior by adding a userevent to control when the unmap can be performed.
It might also fix flakyness in github CI. Not too sure.
> tests/api/images: force unmap/release to be perform after check

- src/queue.cpp
- src/queue_controller.cpp
- src/queue_controller.hpp
In the case where we end up a batch before a flush, we are never updating from flush, which lead to unoptimal batch parameters.
> update batch parameters after flush

- src/context.hpp
- tests/api/printf.cpp
- tests/api/testcl.hpp
Change-Id: Ib27b60fb043e47227f519f34e04316d04f47b55d
> Tweak implementation of cl_arm_printf and introduce dedicated test fixture

- src/queue_controller.cpp
- src/queue_controller.hpp
main updates:
- avoid reducing too much first batch when it is not needed (executor is always busy)
- get out of corner case where first batch is 1
> queue_controller: update dynamic batching

- src/memory.cpp
Return the image_width specified by the cl_image_desc.
The underlying buffer might be bigger than strictly necessary, because the rowPitch might have padding larger than a single pixel.
Therefore, when creating the underlying buffer view, use a view size of element_size() * width() instead of WHOLE_SIZE.
Fixed: #723
> Fix get_image_width() kernel method for 1D texel buffers

- README.md
- src/config.def
- src/device.cpp
This is useful when experimenting with complex applications, without having to modify clvk nor the application.
> add config option to mask device extensions

- src/printf.cpp
This fixes the printf for vectors of size 16 
for example we have this test in the CTS which was previously failing 
```
9)testing printf("%v16o",(1,2,3,4,5,6,7,8,9,0,32,64,128,256,512,1024))                                                                                                           
```
> Fix vector size detection for size 16

- README.md
- src/CMakeLists.txt
- src/config.def
- src/context.cpp
- src/context.hpp
- src/memory.cpp
- src/queue.cpp
- src/queue.hpp
- tests/api/images.cpp
> init image at creation time

- src/kernel.hpp
- src/program.cpp
- src/program.hpp
cvk_entry_point are passed to other structures as a pointer. But it can be deleted at any point when do_build it called.
To avoid invalid access, make entry point a shared_ptr in the program map.
This has been detected running the compiler suite of the CTS on ChromeOS (flaky behaviour).
> fix lifetime of cvk_entry_point

- .github/workflows/presubmit.yml
- tests/config/CMakeLists.txt
- tests/config/run_test.sh
Add the path to the config files in the sources instead.
Ref #743
> do not copy config files to build directory

- docs/supported-applications.md
I've tested DaVinci Resolve and [OpenCL-Benchmark](https://github.com/ProjectPhysX/OpenCL-Benchmark) within a machine with clvk correctly installed (since OpenCL-Benchmark works).
Then, to double check, I've tested the same softwares with the mesa Clover implementation.
The devices generated by clvk are correctly recognized but attempting to do any OpenCL accelerated operation (so basically everything in the software except tweaking the settings) crashes the app instantly.
> Marked "DaVinci Resolve" as Unsupported.

- src/config.def
- src/program.cpp
- src/program.hpp
- tests/api/compiler.cpp
> Add SPIRV Capabilities error in build log

- src/device_properties.cpp
https://github.com/google/clspv/commit/c4f91b91f195cae573aa8bec21af4458b614c9bc translates `mad` to `fma`. 
https://github.com/google/clspv/commit/720be7f459d5695da5fb9acfe70c414090167833 enforces fp32 `fma` unless `fma` is a native builtin.  Together, they prevent radv from doing fp16 packed fma.
This PR adds `fma` to native builtins for AMD.  `clang-format` changes the formatting of the list though.
> add fma to native builtins for AMD

- src/queue.hpp
row_pitch and slice_pitch can be set to '0', which means that it needs to be computed from region values.
> fix cvk_rectangle_copier constructor

- src/api.cpp
- src/device.cpp
- src/device.hpp
- Make reported native and preferred vector widths conditional to support (and do the same for FP16)
- Report cl_khr_fp64 and __opencl_c_fp64 when FP64 is supported
- Always use cvk_device::supports_fp64() to determine support
- Force disable support for now
This fixes compier::features_macro and api::consistency_requirements_fp64 CTS tests.
Change-Id: I454bcb70090aeccf0c7b67911e16745e4728acc9
> Fix FP64 support reporting

- src/device_properties.cpp
This reverts commit 5ab41528149411866d0ea2254e286e6f2f971a07.
Older AMD chips does not have a OpenCL compliant fma native implementation.
But clpeak performance will be fixed for those with https://github.com/google/clspv/commit/eddae278f03941c3da99bbc9c89d370188fb6831
> Revert "add fma to native builtins for AMD (#764)"

- src/config.cpp
- src/config.def
- src/config.hpp
- src/init.cpp
This is needed when logging properties are set in a configuration file.
> Init the logging parts of the config before calling init_logging

- README.md
- src/config.def
- src/device_properties.hpp
This is useful especially with application like clpeak which choose the workload to compute using CL_DEVICE_MAX_COMPUTE_UNITS
> add config to override CL_DEVICE_MAX_COMPUTE_UNITS

- src/api.cpp
According to the OpenCL specification, work_dim can be 0 and work_global_size can be NULL.
https://github.com/KhronosGroup/OpenCL-CTS/issues/2240
> fix clEnqueueNDRangeKernel for NULL work_global_size

- src/CMakeLists.txt
- tests/api/CMakeLists.txt
Make OpenCL-dependencies PRIVATE to avoid unneeded dependencies on target linking with CLLibrary (all the tests)
> cmake: clean CLLibrary link dependencies

- src/api.cpp
When updating OpenCL-Headers to ToT, `api.cpp` now generates a warning (turning into an error in google infrastructure).
> fix warnings in api.cpp following OpenCL-Headers update

- README.md
- src/CMakeLists.txt
- src/tracing.hpp
Building clvk with perfetto within Android build system does not rely at all on the perfetto SDK.
> update cmake to build clvk with perfetto with Android build system

- src/device.cpp
This patch enables the cl_khr_subgroup_shuffle extension.
Change-Id: I52036b4c3fe444afc23b1a3464f997865c534aba
> Add support for cl_khr_subgroup_shuffle extension

- src/program.cpp
test_compiler get_linked_program_info_kernel_names is failing because the test tries to compile the same program twice with different build option (changing a define).
The second time, clvk tries to compile it with `-x ir` because `m_binary_type == CL_PROGRAM_BINARY_TYPE_COMPILED_OBJECT`, which leads to trying to compile a CL source interpret as a IR source.
> fix do_build_inner when compiling a program twice

- src/api.cpp
clSetKernelArg is supposed to fail with CL_INVALID_ARG_SIZE when 0 is passed to a local qualifier kernel argument! (Got CL_SUCCESS, expected CL_INVALID_ARG_SIZE from <OpenCL-CTS>/test_conformance/api/test_kernels.cpp:794)
> fix test_api negative_invalid_arg_size_local

- src/api.cpp
Test expect CL_INVALID_SAMPLER when passing a null pointer to clSetKernelArg for an argument decalred to be of type sampler_t.
> fix test_api negative_invalid_arg_sampler
