kpet/clvk

src/device.hpp, src/program.cpp
With these changes clvk builds on macOS (though I also have hack the OpenCL headers slightly).
=> macOS fixes

src/init.cpp
This checks if the instance actually supports the `VK_EXT_debug_report` extension, instead of unconditionally enabling it. A message is now logged if it was not enabled.
With this change, clvk runs on Talvos with no modifications to either (on Linux). For `simple_test` to work however, the device type needs to be changed from `GPU` to `ALL`.
=> Only enable VK_EXT_debug_report if it is supported

src/api.cpp, src/memory.hpp
Enough to pass the clGetInfo conformance test.
=> Implement basic clGetImageInfo

.gitmodules, CMakeLists.txt, src/CMakeLists.txt
=> Add support to use Talvos as the vulkan implementation

src/kernel.cpp, src/program.cpp, src/program.hpp, tests/simple_ubo/CMakeLists.txt, tests/simple_ubo/simple.cpp
Fixes #30
* Added parsing and processing support for buffer_ubo arg kind
* Generates uniform buffer
* Added simple test that exercises new buffer type
* Fix compile error on Mac
=> Add support for buffer_ubo args

src/api.cpp, src/kernel.cpp, src/kernel.hpp, src/queue.cpp, src/queue.hpp, tests/conformance/results-kpet.json
This is incomplete and there is definitely scope for refactoring this into better code but this patch does enable quite a few applications to run.
Fixes #8.
=> Basic support for kernel arguments in local address space

src/api.cpp, tests/api/CMakeLists.txt, tests/api/images.cpp, tests/api/testcl.hpp
=> Support legacy image creation entrypoints

README.md, doc/supported-applications.md
=> Document supported applications in a separate file

src/api.cpp, src/device.hpp, src/memory.cpp, src/memory.hpp, src/queue.cpp, src/queue.hpp, tests/api/images.cpp, tests/api/testcl.hpp
Now enabling support for images.
Closes #86.
=> Basic support for mapping/unmapping images

src/api.cpp, src/queue.cpp
=> Support clEnqueue{Read,Write}Image

src/api.cpp, src/memory.hpp, src/queue.cpp, src/queue.hpp
=> Implement clEnqueueCopyImage

src/memory.hpp, tests/api/testcl.hpp
One of these would have been caught earlier if there was a Clang configuration in Travis - @kpet is this something we can add or were you hoping to get Clang coverage via a macOS configuration?
=> Build fixes

.travis.yml
=> Re-enable macOS in Travis CI

src/vkutils.hpp
Needs CHECK_RETURN from utils.hpp.
=> Add missing include for vkutils.hpp

.clang-format, tests/travis/step-before-install.sh
=> Remove the need for Clang 10 for code formatting

.travis.yml, tests/travis/step-before-install.sh, tests/travis/step-install.sh
Should speed up builds and reduce clang-format pain.
=> Move Travis CI to Ubuntu 18.04

.clang-format, src/kernel.cpp, src/kernel.hpp, src/program.cpp, src/program.hpp, src/queue.cpp, src/queue.hpp
=> Basic support for literal samplers and multiple descriptor sets

src/device.cpp, src/device.hpp, src/program.cpp, src/program.hpp
=> Allow standard layout in uniform buffers when supported

src/api.cpp, src/device.cpp, src/device.hpp, src/init.cpp
=> Add support for cl_khr_extended_versioning

src/api.cpp, src/device.cpp, src/kernel.cpp, src/program.cpp, src/program.hpp, src/queue.cpp, src/queue.hpp, tests/conformance/results-kpet.json
=> Support for global offset and get_work_dim()

src/api.cpp, src/device.cpp
=> Support cl_khr_create_command_queue

README.md, azure-pipelines.yml, tests/azure/steps-build.yml, tests/azure/steps-fetch-sources.yml
=> Add Windows CI using Azure Pipelines

src/program.cpp, src/program.hpp, src/queue.cpp, tests/api/enqueue.cpp, tests/api/testcl.hpp
=> Support kernels with no arguments

src/api.cpp, src/memory.hpp, src/queue.cpp, src/queue.hpp, tests/conformance/results-kpet.json
- Introduce a mapping object (similar to images)
- Fix handling of CL_MEM_USE_HOST_PTR
Fixes #64
=> Rework/fix buffer mapping/unmapping

src/api.cpp, src/device.cpp, src/device.hpp, src/exports.map, src/init.hpp, src/log.cpp, src/log.hpp, src/queue.cpp, src/queue.hpp, tests/api/main.cpp, tests/api/profiling.cpp, tests/api/testcl.hpp
Fixes #165
Also fix a couple of trivial Windows build issues.
=> Support device and host timer functions

src/cl_headers.hpp, src/memory.cpp
=> Support CL_HALF_FLOAT in clEnqueueFillImage

src/api.cpp
Fix device enqueue capability query.
=> Update OpenCL Headers

src/api.cpp, src/device.cpp, src/device.hpp
=> Update extended versioning for OpenCL 3

src/kernel.hpp, src/program.cpp, src/program.hpp, tests/api/enqueue.cpp
...for resources with a binding greater than the number of resources.
Fixes #233
=> Fix argument resource indexing

src/api.cpp, src/exports.map, src/kernel.cpp, src/kernel.hpp
=> Implement clCloneKernel

src/api.cpp, src/device.cpp, src/device.hpp
Also introduce a generic function to retrieve Vulkan properties.
Fixes #249
=> Support cl_khr_device_uuid

src/api.cpp
=> Add all missing core entry points from all versions

src/api.cpp, src/queue.cpp, src/queue.hpp
=> Support CL_QUEUE_PROPERTIES_ARRAY

README.md, src/api.cpp, src/device.cpp, src/device.hpp, src/queue.cpp, src/queue.hpp, tests/api/profiling.cpp, tests/api/testcl.hpp
=> Complete queue profiling support

src/queue.cpp
Signed-off-by: Judicaël CLAIR <judicael.clair@arm.com>
=> Added further details when exceeding workgroup size limits

src/api.cpp, src/program.cpp, src/program.hpp, src/utils.cpp, src/utils.hpp, tests/api/CMakeLists.txt, tests/api/compiler.cpp, tests/api/testcl.hpp
=> Support CL_PROGRAM_BUILD_LOG

CMakeLists.txt, src/CMakeLists.txt
=> Tentatively re-enable SPIR-V consumption on Windows

src/device.cpp
This requires 16-bit storage and shaderFloat16.
=> Enable cl_khr_fp16 if the device can support it

src/memory.cpp
The behavior of float->int conversion when the value is out-of-range or NaN is undefined, so manually handle NaN and clamp the value first.
With this change (and #276), the full `clFillImage` CTS suite passes on NVIDIA for me.
=> Fix float->int conversion UB in clEnqueueFillImage

src/memory.cpp
Tested with the `clFillImage` suite in CTS.
=> Handle CL_LUMINANCE in clEnqueueFillImage

src/api.cpp, src/device.cpp, tests/conformance/results-kpet.json
=> Add support for cl_khr_suggested_local_work_size

src/api.cpp, src/memory.cpp
=> Fix kernel-side access to CL_LUMINANCE images

CMakeLists.txt, src/CMakeLists.txt, src/api.cpp, src/device.cpp, src/device.hpp, src/init.cpp, src/init.hpp, src/program.cpp, src/program.hpp, tests/api/CMakeLists.txt, tests/api/compiler.cpp, tests/api/profiling.cpp, tests/api/testcl.hpp, tests/azure/job-precommit.yml, tests/azure/pipeline-precommit.yml, tests/azure/steps-build.yml, tests/azure/steps-run-tests.yml, tests/simple-from-binary/CMakeLists.txt, tests/simple-from-binary/simple.cl, tests/simple-from-binary/simple.cpp
=> Add build configuration with compiler entirely disabled

README.md, tests/azure/job-precommit.yml, tests/azure/pipeline-precommit.yml, tests/azure/steps-build.yml, tests/azure/steps-fetch-sources.yml, tests/azure/steps-get-android-ndk.yml, tests/azure/steps-run-tests.yml, tests/azure/steps-setup-ccache.yml
=> Add instructions and CI for Android

src/device.cpp, src/device.hpp, src/program.cpp, src/program.hpp, src/utils.cpp, tests/api/compiler.cpp
Adds support for SPIR-V 1.3, 1.4 & 1.5.
=> Select target SPIR-V environment dynamically

src/api.cpp, src/kernel.hpp, src/program.cpp, src/program.hpp
Fixes #51
Also update clspv and CTS
=> Implement clGetKernelArgInfo

tests/conformance/results-kpet.json
Fixes #62 
Fixes #79
Fixes #80
=> Update deps and CTS

src/program.cpp
clspv is based on LLVM.
LLVM options parsing is done using global variable that are not thread safe.
Thus, we need to lock call to clspv in order to ensure a thread safe execution.
=> lock call to clspv to be thread-safe

src/program.cpp
Updates clspv to include google/clspv#823, which provides support
for input languages other than OpenCL. This allows for using the
CompileFromSourceString api for IL binaries rather than needing
to use temporary files. This resolves the final review comment
in #343.
@dcastagna @jrprice
=> Compile IL binaries without temp files in online mode

.github/workflows/build-swiftshader.yml, .github/workflows/presubmit.yml, CMakeLists.txt, README.md, tests/CMakeLists.txt, tests/azure/pipeline-precommit.yml
=> Migrate CI to Github Actions

docs/supported-applications.md
=> Document BOINC supports clvk

src/api.cpp, src/device.cpp, src/device.hpp, src/kernel.hpp, src/program.cpp, src/program.hpp, src/queue.cpp, src/utils.hpp, tests/conformance/results-kpet.json
=> Support cl_khr_subgroups and core subgroup feature

README.md, src/api.cpp, src/event.hpp, src/kernel.hpp, src/memory.cpp, src/memory.hpp, src/program.hpp, src/queue.cpp, src/queue.hpp, src/vkutils.hpp, tests/api/images.cpp, tests/api/testcl.hpp, tests/conformance/results-kpet.json
Fixes #108
Fixes #121
Fixes #271
Fixes #107 
Signed-off-by: James Price <jrprice@google.com>
=> Basic support for initial image layout transition and images with host ptr

src/kernel.cpp, src/kernel.hpp, src/program.cpp, src/program.hpp, src/queue.cpp, tests/api/images.cpp, tests/api/testcl.hpp
Update clspv and SPIRV-Headers
=> add support for get image channel order and data type

src/queue.cpp, src/queue.hpp
=> Fix assertion in and clarify design of data movement commands

.github/workflows/presubmit.yml, CMakeLists.txt, README.md, src/queue.cpp
=> Add a build option to control asserts and enable in CI

src/program.cpp, tests/api/compiler.cpp, tests/api/testcl.hpp
this will help pass all compiler tests of the CTS
Ref #391
=> fix save string to file when a folder is missing in the path

src/program.cpp
PR #432 added the possibility to create folder inside the temp folder for include purpose. But the folders created for that are not added to the temp stack. This create the unwanted behavior of leaving the temp folder on disk everytime this feature is used.
I thought of just adding it to the deletion stack, but it was complicated a bit the code, and I did not see any good reason to erase everything in the temp folder invididualy.
I propose to remove everything in the folder using filesystem::remove_all.
=> fix temp folder content deletion

src/device.cpp
#435 correctly started requiring shaderSubgroupExtendedTypes to report cl_khr_subgroups as supported.
The extension that introduced it was, correctly, only being requested for versions of Vulkan prior to 1.2 where it was promoted to a core feature.
The feature query code only performed queries for features provided by an extension which meant that, on a 1.2+ implementation, the feature was reported as VK_FALSE and thus cl_khr_subgroups was no longer reported.
Feature queries are now run as well for features from extensions that have been promoted to a core Vulkan version.
=> Handle feature queries for promoted Vulkan extensions

README.md
This keeps catching me out! :sweat_smile:
=> Update CLSPV_PATH in README

src/program.cpp, src/program.hpp, tests/api/compiler.cpp
Use LLVM IR as the intermediate language
clCompileProgram generated a LLVM IR binary.
clLinkProgram takes LLVM IR binaries as inputs and generates a SPIRV binary.
cvk_program stores the LLVM IR in the new argument 'm_ir'.
Based on google/clspv#932
Ref #391
=> add full support for clLinkProgram

src/program.cpp, src/program.hpp
=> Tidy up the compiler interface code a bit

src/api.cpp, src/device.cpp, src/event.cpp, src/event.hpp, src/queue.cpp, src/queue.hpp
it will help to introduce timeline semaphore
=> refactor profiling into event

src/event.cpp, src/queue.cpp, src/queue.hpp, tests/conformance/results-kpet.json
=> A few tweaks to the event profiling refactor

src/device.cpp, src/device.hpp, src/memory.hpp, tests/CMakeLists.txt
Also fix test build with non-loader Vulkan implementation.
Fixes #491
=> Do not assume vkGetBufferDeviceAddress is available to link against

src/CMakeLists.txt, src/api.cpp, src/device.cpp, src/icd.hpp, src/log.cpp, src/objects.hpp, src/semaphore.cpp, src/semaphore.hpp
Change-Id: If1e170d460391ed4a3c0132d6ce4797d35dcf557
=> Add API boilerplate for cl_khr_semaphore

src/api.cpp, src/program.cpp, src/program.hpp
Change-Id: I1cab0013013633b3b9fc480e3f7716478667b285
=> Implement clSetProgramSpecializationConstant

.github/workflows/presubmit.yml, src/api.cpp
This is breaking in Google infra
=> remove extra parentheses

.github/workflows/presubmit.yml
Change-Id: I1d5e9de578be82f15d024c3dfe5e9d0691e99a72
=> ci: fix issues in Android job

src/api.cpp, src/device.cpp, src/program.cpp
Update `clspv` to get address space support
=> Add generic address space support

README.md, src/api.cpp, src/config.def, src/event.cpp, src/event.hpp, src/log.cpp, src/log.hpp, src/objects.hpp
Change-Id: I83dfcd4dbb3fb932b47c4ffc204a8c449976d47f
=> Support for categorising log messages using groups

src/memory.hpp
Change-Id: Id46f659dcb1859b6a1d0a3dba99bc4299f9d44e7
=> Set correct usage and memory allocation flags for physical addressing

src/api.cpp, tests/conformance/results-amd-7950x.json, tests/conformance/results-intel-a750.json
Also update clspv
Change-Id: I4c07e37f78f342fc093ec11acfa102c3e98e9328
=> Check context validity in clGetContextInfo

README.md
=> Explain building for Rapsberry Pi.

src/memory.cpp
Flagged by validation layers.
Change-Id: I49451d08464fbfe36dc94a721d9d377b3a1a7104
=> Prevent creation of invalid samplers with unnormalized coordinates

.github/actions/install-vulkan-sdk/action.yml, .github/workflows/presubmit.yml, src/init.cpp, src/log.cpp, src/log.hpp
Fixes #355
Change-Id: I689d7b816550f48f3a7049d42336df599f59d827
=> ci: add run of API tests under validation layers

.github/workflows/presubmit.yml
1.3.250.0 is not available on the website anymore
=> update vulkan package to 1.3.250.1 for windows

.github/actions/setup-ninja/action.yml, .github/workflows/build-swiftshader.yml, .github/workflows/presubmit.yml
Change-Id: I9a5dc32ac50c6c8654d7d7767c5f4a1d4b7706ef
=> ci: add composite action to set up Ninja

src/printf.cpp, tests/api/printf.cpp
stop printing if the args size overflows the printf buffer size
add a new test
=> fix printf when reaching the end of the printf buffer

CMakeLists.txt, README.md
Change-Id: I8204ce7a25a34c85c71e2a851597536dd2a4b0cd
=> Add build options to enable sanitizers

src/device.hpp
Change-Id: I95b303a4a6116263ad56a26d4aa8c72fe14ca3d1
=> Make Vulkan queue allocation thread safe

docs/supported-applications.md, src/program.cpp
=> Quote application-provided build options for the shell used to invoke clspv

.github/actions/install-vulkan-sdk/action.yml, .github/workflows/presubmit.yml
My PR needed for recent SDK versions was merged.
Change-Id: I8f82132b6243e1868549e97e396be14ab036ade6
=> ci: use upstream install-vulkan-sdk action

src/device.hpp
When maxMemoryAllocationSize is bigger than CLVK_MEM_MAX_ALLOC_SIZE_MB default value (1024MB), we need to use it, not lower it to 1024MB for no reason.
Also, avoid calling 3 times global_mem_size in max_mem_alloc_size. This is printing 3 times the same log (from global_mem_size) when calling max_mem_alloc_size.
=> fix max_mem_alloc_size

src/device_properties.cpp
As was mentioned earlier https://github.com/kpet/clvk/pull/517#issuecomment-1534970787 went back and corrected our list.
=> Update device properties for Samsung device with native builtins

src/queue.cpp, src/queue.hpp
Fixes #658
Change-Id: Ib2af3a179e7e173d21d8fcc0477c1c8ec43a877d
=> Use RAII to manage exclusive access to command pools

src/api.cpp
https://github.com/KhronosGroup/OpenCL-CTS/pull/1850
=> fix clGetMemObjectInfo of CL_MEM_HOST_PTR after fix in CTS

README.md, src/config.cpp, src/init.cpp
Change-Id: I359515fb1decf5cced112587c4d4c58e46414448
=> Tidy up and document support for config files

src/device.cpp
On some platform (like AMD), compute only queues have longer timeouts than universal queues (compute & graphics queues).
Thus, using universal queues can lead to GPU hung while we don't have them with compute only queues.
=> favour compute only queues over universal queues

src/device.hpp
Some devices have a device_local & host_coherent memory before the device_local memory in their list. This lead clvk to choose an suboptimal memory for images impacting performances.
=> Favor uncoherent memory for images

src/api.cpp, src/memory.hpp, src/queue.cpp, src/queue.hpp, tests/api/images.cpp
=> fix image1d_buffer refcounting with map/unmap cmds

src/log.cpp
=> Support building on Debian 11

README.md, src/config.def, src/init.cpp
=> Add option to control whether global state is destroyed

src/device.hpp, src/memory.cpp, src/memory.hpp, src/printf.cpp, src/queue.cpp, src/queue.hpp
=> add support for uncoherent cached memory

src/printf.cpp, tests/api/printf.cpp
This change fixes the functionality related to printf of vectors of size 16
=> 714-2 Fix vector 16 printf

CMakeLists.txt
This is causing issues with android build
=> cmake: Disable clspv spirv build

src/api.cpp, src/device.cpp, src/device.hpp, src/kernel.hpp, tests/api/subgroup_size.cpp, tests/api/testcl.hpp
Respect maxComputeWorkgroupSubgroups limit
Change-Id: I1242c9bf13dbd10dfc87351767a6698e1fa8879c
=> Fix validation error in WithCommandQueue.SubgroupSize

src/device.hpp
=> return zero for CL_DEVICE_DOUBLE_FP_CONFIG

.github/workflows/presubmit.yml
Change-Id: Ib4f6ec512e16a33b1684f440acdfeea2629056d3
=> ci: fix macOS jobs

src/kernel.cpp, src/program.cpp, src/program.hpp, tests/api/local_buffer.cpp, tests/api/testcl.hpp
parse clspv NonSemanticClspvReflectionWorkgroupVariableSize and add it to the local memory size needed by a kernel
=> fix reporting of CL_KERNEL_LOCAL_MEM_SIZE

src/api.cpp
- CL_PROGRAM_NUM_KERNELS
- CL_PROGRAM_KERNEL_NAMES,
- CL_PROGRAM_SCOPE_GLOBAL_CTORS_PRESENT
- CL_PROGRAM_SCOPE_GLOBAL_DTORS_PRESENT
Those params requires the program to have been built for at least one device according to the specification.
Returning the value when the program has not been built triggers a failure in the CTS (compiler get_program_info_kernel_names).
=> fix clGetProgramInfo for some param_names

src/memory.hpp, src/queue.cpp, src/queue.hpp, tests/api/dependencies.cpp
Fixes #553
Change-Id: Idc4c9c3a224f63a733fb07dd5917bf90819b957b
=> Clean up image mappings when image mapping commands fail

src/device.cpp, src/device.hpp, src/queue.hpp
- Protect cvk_device internal values with mutex
- Update cvk_device internal values at START time
Ref #783
=> update device_host_timer management
